language: java
sudo: enabled

notifications:
  email: false

# git history is not needed during build
git:
  depth: false

services: docker

env:
  global:
    # GH_TOKEN - GitHub automated release token
    secure: "eHVjZ4S7sSnNffbT4rBTvmE8Z2B0uh8xpwu7gEUsxmDVpa5w+CmRRECeSaae6v3+1BMnBhs2vxcN0OrtEFt8tFzqD/PMqql8cwT5PTS/i6HsRJyjH5opRNyQ/FeYmbYGPBecTA4OdvZtO4P1pIIBEKxTzqUA++VhVWF3nWinEbrBQWqWdpYM6WxYTXNISYF7os49ohnpemCjRjPc13V8vGZnguRy0UD4ZFg/67l6b4ebYbcOHLoNw6K8xg98x0BxjwQnwvEXN8eXbxBUDPIiPBR2BawCvSNh5snhzFpLN1caV43RsUq+SajbRfu8YuiGpOaxTqL59AX62YEvPJqIsvcxjvcSnNglZrz0lVj6emfzFJJhKlmkVZ4jxhmnQ5QFx3OSQRWi4lJ2i+obEDoPvRn3NCDau66rWQ+MnbSS6kxpWYw6j/ea6R+BGC5x81bSROHbEH+2UHOW9iRihnbK+E4Ozqjr3TYXMSOeC6bx+TgX90MfdM0tjDxKu7wWaYZ37fIOFBqs2pRgUz8E06MEcTb1t9tsxnZF+i3siTpmO9aN+GAZvScmbrHiDLKcXCx6DLdAaEvViJynpxqIBu+cXMarIiV4engdRiU16CxkxaJ8MJSD7Dt7oRvd4bSG2fWjiVTjue/yUgiua+v9qelSwEeqAoLulgaqNtdtK8Rjxd4="


# Avoid config duplication via yaml anchors
_stf_setup_config: &stf_before_script
  if: type in (cron, api)
  # variable is only used for allow_failures
  env: J_TYPE=STF_TEST
  before_script:
    # Pull required images
    - docker pull saros/build_test:0.1
    - docker pull saros/stf_test_master:0.1
    - docker pull saros/stf_test_slave:0.1
    - docker pull saros/stf_xmpp_server:0.1
    # Create shared workspace dir which is mounted by the build, master and slave containers
    - mkdir stf_ws
    # Build required artifacts and move them in the shared workspace
    - docker run -t -v $PWD:/home/saros/ci/saros_src -v $PWD/stf_ws:/home/saros/ci/stf_ws saros/build_test:0.1 /home/saros/ci/saros_src/travis/script/stf/build/provide_testee.sh
    # Start required containers and services
    - export CONFIG_DIR=travis/config SCRIPT_DIR=travis/script/stf; $PWD/travis/script/stf/setup_stf_container.sh $PWD

jobs:
  # Dont report failures on master branch commits if stf tests fail
  allow_failures:
    - env: J_TYPE=STF_TEST
  include:
    # Always build, but deploy only on master branch during a cron job
    - before_script: docker pull saros/build_test:0.1
      script:
        - docker run -v $PWD:/home/saros/ci/saros_src saros/build_test:0.1 /home/saros/ci/saros_src/travis/script/build/build_all.sh
      after_success:
        - sonar-scanner
      before_deploy:
        - sudo apt-get update
        - sudo apt-get install jq
      deploy:
        provider: script
        script: export SCRIPT_DIR=travis/script/deploy; travis/script/deploy/release_daily.sh $GH_TOKEN $TRAVIS_REPO_SLUG $TRAVIS_BRANCH
        on:
          branch: master
          condition: $TRAVIS_EVENT_TYPE = cron

    - <<: *stf_before_script
      script: docker exec -t stf_master scripts/start_stf_tests.sh

    - <<: *stf_before_script
      script: docker exec -t stf_master scripts/start_stf_self_tests.sh
